---
title: "WA State Claims Data - LNI data request"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    #source_code: embed
    theme: cerulean
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(pacman)
p_load(datasets, ggplot2, data.table, shiny, shinyWidgets, readxl,scales, plyr,stringr,DT,highcharter, broom, flexdashboard)

soc = setDT(read.csv("soc-structure-2000.csv"))

data = data.table(read_excel("../LNI data request/130656-Records.xlsx", sheet = "SF Claims Data"))

data$`Oiics Accdt Type Code 3` = str_pad(data$`Oiics Accdt Type Code 3`, 3, pad = "0")

denom = data.table(read_excel("../LNI data request/130656-Records.xlsx", sheet =  " SF Hours Class 7301-00", skip = 3))
setnames(denom, c("year", "acct.id.q1","total.hours.q1",
                  "acct.id.q2","total.hours.q2",
                  "acct.id.q3","total.hours.q3",
                  "acct.id.q4","total.hours.q4"))
denom[, total.hours := total.hours.q1 + total.hours.q2 + total.hours.q3 + total.hours.q4]
denom[, worker_n := total.hours/(200000/100)]
denom[, acct.id := rowMeans(.SD), .SDcols = c("acct.id.q1", "acct.id.q2",
                                        "acct.id.q3", "acct.id.q4")]

myvals = data.table(soc2k = "temp", type = "temp")

myvals = lapply(unique(data[!is.na(`Soc2K Code Description`)]$`Soc2K Code Description`), 
       FUN = function(value){
  temp = unlist(grep(value, unique(soc$Management.Occupations), value = TRUE))[1]
  temp1 = data.table(soc2k = temp, type = value)
  temp1
})

myvals = rbindlist(myvals)
myvals = myvals[!is.na(soc2k) & !is.na(type)]

setkey(myvals, type)
setkey(data, `Soc2K Code Description`)
data = myvals[data]
data[, `Soc2K Code Description` := soc2k]

#data = data[!is.na(`Soc2K Code Description`)]
#
#create OIICS code list
#

oiics_source = readRDS("oiics_source.RDS")
oiics_nature = readRDS("oiics_nature.RDS")
oiics_bp = readRDS("oiics_bp.RDS")
oiics_event = readRDS("oiics_event.RDS")

data[, year := as.numeric(as.character((`Injry Date Year`)))]
data = data[`Risk Main Sub` == "730100", ]
data[,"Days Paid" := `Clm Tl Day Pd Drvd Qty`]


```


Inputs {.sidebar data-width=300}
===============================


```{r}

#add cost/injury
##add link to OIICS descriptions
#increase font
#add tooltip
#add masking to circumstances tool
#is there is difference in coding practice by time?
#add overall trend line

#width of pickerInput
widthPI = 22

my_choicesStatus <- data.table(choices = str_to_title(unique(data$`Status Desc`)))
#setkey(my_choicesStatus, choices)
my_choicesStatus2 = unique(data$`Status Desc`)
names(my_choicesStatus2) <-
  stringr::str_wrap(my_choicesStatus$choices, exdent = 2, width = widthPI)
names(my_choicesStatus2) <- stringr::str_replace_all(names(my_choicesStatus2),
                                               "\\n", "<br> &nbsp")

pickerInput('status', 'Claims Status', unique(my_choicesStatus2),
               selected = unique(my_choicesStatus2), multiple = T,
                        options = list(
      `actions-box` = TRUE, size = 10,
      `selected-text-format` = "count > 5",
      `live-search`=TRUE),
      choicesOpt = list(
      content = names(my_choicesStatus2)
    ))

selectInput('ycol', 'Plotting Variable', choices = 
              list("Claims Rate (per 100 workers)" = "Claims Rate",
                   "Number of Claims" = "Number of Claims",
                   "Cost ($)" = "Total Cost",
                   "Paid Days Off" =  "Days Paid"),
            selected="Claims Rate", multiple = F)

sliderInput("year", "Year:",
            min = min(data$year), max = max(data$year),
            step = 1,
            value = c(min(data$year),
                      max(data$year)))

sliderInput("mincases", "Minimum number of Cases:", min = 1,
            max = round_any(50,10, ceiling),
            step = 10,
            value = 1)

my_choices <- data.table(choices = paste0(oiics_nature$CASE_CODE_TITLE, ": ",
                    oiics_nature$CASE_CODE),
                    CASE_CODE = oiics_nature$CASE_CODE,
                    keyval = oiics_nature$CASE_CODE_TITLE,
                    hier = nchar(oiics_nature$CASE_CODE))
setkey(my_choices, hier, CASE_CODE)
my_choices2 <- as.list(my_choices$CASE_CODE)
names(my_choices2) <-
  stringr::str_wrap(my_choices$choices, exdent = 2, width = widthPI)
names(my_choices2) <- stringr::str_replace_all(names(my_choices2),
                                               "\\n", "<br> &nbsp")

pickerInput("nature", "Nature:",
            choices = my_choices2,
            selected = my_choices2,
            multiple = T,
            options = list(
      `actions-box` = TRUE, size = 10,
      `selected-text-format` = "count > 5",
      `live-search`=TRUE),
      choicesOpt = list(
      content = names(my_choices2)
    ))

my_choices <- data.table(choices = paste0(oiics_bp$CASE_CODE_TITLE, ": ",
                    oiics_bp$CASE_CODE),
                    CASE_CODE = oiics_bp$CASE_CODE,
                    keyval = oiics_bp$CASE_CODE_TITLE,
                    hier = nchar(oiics_bp$CASE_CODE))
setkey(my_choices, hier, CASE_CODE)
my_choices2 <- as.list(my_choices$CASE_CODE)
names(my_choices2) <-
  stringr::str_wrap(my_choices$choices, exdent = 2, width = widthPI)
names(my_choices2) <- stringr::str_replace_all(names(my_choices2),
                                               "\\n", "<br> &nbsp")
pickerInput("bp", "Body Part:",
            choices = my_choices2,
            multiple = T,
            selected = my_choices2,
            options = list(
      `actions-box` = TRUE, size = 10,
      `selected-text-format` = "count > 5",
      `live-search`=TRUE),
      choicesOpt = list(
      content = names(my_choices2)
    ))


my_choices <- data.table(choices = paste0(oiics_source$CASE_CODE_TITLE, ": ",
                    oiics_source$CASE_CODE),
                    CASE_CODE = oiics_source$CASE_CODE,
                    keyval = oiics_source$CASE_CODE_TITLE,
                    hier = nchar(oiics_source$CASE_CODE))
setkey(my_choices, hier, CASE_CODE)
my_choices2 <- as.list(my_choices$CASE_CODE)
names(my_choices2) <-
  stringr::str_wrap(my_choices$choices, exdent = 2, width = widthPI)
names(my_choices2) <- stringr::str_replace_all(names(my_choices2),
                                               "\\n", "<br> &nbsp")

pickerInput("source", "Source:",
            choices = my_choices2,
            selected = my_choices2,
            multiple = T,
            options = list(
      `actions-box` = TRUE, size = 10,
      `selected-text-format` = "count > 5",
      `live-search`=TRUE),
      choicesOpt = list(
      content = names(my_choices2)
    ))



my_choices <- data.table(choices = paste0(oiics_event$CASE_CODE_TITLE, ": ",
                    oiics_event$CASE_CODE),
                    CASE_CODE = oiics_event$CASE_CODE,
                    keyval = oiics_event$CASE_CODE_TITLE,
                    hier = nchar(oiics_event$CASE_CODE))
setkey(my_choices, hier, CASE_CODE)
my_choices2 <- as.list(my_choices$CASE_CODE)
names(my_choices2) <-
  stringr::str_wrap(my_choices$choices, exdent = 2, width = widthPI)
names(my_choices2) <- stringr::str_replace_all(names(my_choices2),
                                               "\\n", "<br> &nbsp")
pickerInput("event", "Event:",
            choices = my_choices2,
            selected = my_choices2,
            multiple = T,
            options = list(
      `actions-box` = TRUE, size = 10,
      `selected-text-format` = "count > 5",
      `live-search`=TRUE),
      choicesOpt = list(
      content = names(my_choices2)
    ))





```

General Claims Descriptions
===================================== 

Column {.tabset}
-----------------------------------------------------------------------
###Nature

```{r}

selectedData <- reactive({
  newdata = copy(data)
  newdata = newdata[year %in% input$year[1]:input$year[2] &
                      newdata$`Status Desc` %in% input$status & 
                      (newdata$`Oiics Srce Code 1` %in%
                         input$source |
                        newdata$`Oiics Srce Code 2` %in%
                         input$source |
                         newdata$`Oiics Srce Code 3` %in%
                         input$source |
                          newdata$`Injry Oiics Srce Code` %in%
                         input$source) & 
                      (newdata$`Oiics Nat Code 1` %in%
                         input$nature |
                        newdata$`Oiics Nat Code 2` %in%
                         input$nature |
                         newdata$`Oiics Nat Code 3` %in%
                         input$nature |
                          newdata$`Injry Oiics Nat Code` %in%
                         input$nature) &
                      (newdata$`Oiics Body Part Code 1` %in%
                         input$bp |
                        newdata$`Oiics Body Part Code 2` %in%
                         input$bp |
                         newdata$`Oiics Body Part Code 3` %in%
                         input$bp |
                          newdata$`Injry Oiics Body Part Code` %in%
                         input$bp) &
                       (newdata$`Oiics Accdt Type Code 1` %in%
                         input$event |
                        newdata$`Oiics Accdt Type Code 2` %in%
                         input$event |
                         newdata$`Oiics Accdt Type Code 3` %in%
                         input$event |
                          newdata$`Injry Oiics Accdt Type Code` %in%
                         input$event),]
  
  newdata
})

naturetable <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)/1000),
     by = c( "Oiics Nat Code Desc 2") ][`Number of Claims`>=input$mincases,]
temp[, `Claims Rate` := round(`Number of Claims`/(sum(denom[year %in% input$year[1]:input$year[2],]$total.hours)/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, "Oiics Nat Code Desc 2", "Description")
temp
})
  
                      
  
renderDataTable(datatable(naturetable()  , options = list(pageLength = 10,
                                                          class = "display nowrap")) %>% 
         formatCurrency(c("Total Cost"), digits = 0, currency = "K $", 
         before = FALSE) %>%
      formatStyle(input$ycol, backgroundColor = 'yellow'))

natureplot <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = sum(`Days Paid` ),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)),
     by = c( "Oiics Nat Code Desc", "year") ][`Number of Claims`>=((input$year[2]-input$year[1])/2+1),]
  setkey(temp, year)
  setkey(denom, year)
  temp = denom[temp]
temp[, `Claims Rate` := round(`Number of Claims`/(total.hours/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, input$ycol, "yval")
setnames(temp, "Oiics Nat Code Desc", "Description")
temp = temp[!is.na(Description) & Description %in% unique(temp$Description)[1:11]]
temp
})



```

###Body Part
```{r}

bptable <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)/1000),
     by = c( "Oiics Body Part Code Desc") ][`Number of Claims`>=input$mincases,]
temp[, `Claims Rate` := round(`Number of Claims`/(sum(denom[year %in% input$year[1]:input$year[2],]$total.hours)/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, "Oiics Body Part Code Desc", "Description")
temp
})

renderDataTable(datatable(bptable()  , options = list(pageLength = 10,
                                                          class = "display nowrap")) %>% 
         formatCurrency(c("Total Cost"), digits = 0, currency = "K $", 
         before = FALSE) %>%
      formatStyle(input$ycol, backgroundColor = 'yellow'))

bpplot <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)),
     by = c( "Oiics Body Part Code Desc", "year") ][`Number of Claims`>= (input$mincases)/((input$year[2]-input$year[1])/2+1),]
# temp[, `Claims Rate` := round(`Number of Claims`/(sum(denom[year %in% input$year[1]:input$year[2],]$total.hours)/200000),2)]
setkey(temp, year)
  setkey(denom, year)
  temp = denom[temp]
temp[, `Claims Rate` := round(`Number of Claims`/(total.hours/200000),2)]
  
setorderv(temp, input$ycol, order = -1)
setnames(temp, input$ycol, "yval")
setnames(temp, "Oiics Body Part Code Desc", "Description")
temp = temp[!is.na(Description) & Description %in% unique(temp$Description)[1:11]]
temp
})

```

###Source
```{r}

sourcetable <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)/1000),
     by = c( "Oiics Srce Code Desc") ][`Number of Claims`>=input$mincases,]
temp[, `Claims Rate` := round(`Number of Claims`/(sum(denom[year %in% input$year[1]:input$year[2],]$total.hours)/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, "Oiics Srce Code Desc", "Description")
temp
})

renderDataTable(datatable(sourcetable()  , options = list(pageLength = 10,
                                                          class = "display nowrap")) %>% 
         formatCurrency(c("Total Cost"), digits = 0, currency = "K $", 
         before = FALSE) %>%
      formatStyle(input$ycol, backgroundColor = 'yellow'))

sourceplot <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)),
     by = c( "Oiics Srce Code Desc", "year") ][`Number of Claims`>= (input$mincases)/((input$year[2]-input$year[1])/2+1),]
setkey(temp, year)
  setkey(denom, year)
  temp = denom[temp]
temp[, `Claims Rate` := round(`Number of Claims`/(total.hours/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, input$ycol, "yval")
setnames(temp, "Oiics Srce Code Desc", "Description")
temp = temp[!is.na(Description) & Description %in% unique(temp$Description)[1:11]]
temp
})


```

###Event
```{r}

eventtable <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)/1000),
     by = c( "Oiics Accdt Type Code Desc") ][`Number of Claims`>=input$mincases,]
temp[, `Claims Rate` := round(`Number of Claims`/(sum(denom[year %in% input$year[1]:input$year[2],]$total.hours)/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, "Oiics Accdt Type Code Desc", "Description")
temp
})

renderDataTable(datatable(eventtable()  , 
                          options = list(pageLength = 10,
                                         class = "display nowrap")) %>% 
         formatCurrency(c("Total Cost"), digits = 0, currency = "K $", 
         before = FALSE) %>%
      formatStyle(input$ycol, backgroundColor = 'yellow'))


eventplot <- reactive({
  temp = selectedData()[, list(`Number of Claims` = 
              length(unique(`Pseudo Claim Id`)),
              `Days Paid` = 
              sum(`Days Paid`),
              `Total Cost` = 
              sum(`Actuary Incur Tot`)),
     by = c( "Oiics Accdt Type Code Desc", "year") ][`Number of Claims`>= (input$mincases)/((input$year[2]-input$year[1])/2+1),]
setkey(temp, year)
  setkey(denom, year)
  temp = denom[temp]
temp[, `Claims Rate` := round(`Number of Claims`/(total.hours/200000),2)]
setorderv(temp, input$ycol, order = -1)
setnames(temp, input$ycol, "yval")
setnames(temp, "Oiics Accdt Type Code Desc", "Description")
temp = temp[!is.na(Description) & Description %in% unique(temp$Description)[1:11]]
temp
})


```

Time Series Plot
=============================


Column {.tabset}
-----------------------------------------------------------------------
###Nature

```{r}

renderHighchart ({
  
 naturevalues = natureplot()
 
 if(nrow(naturevalues)>1){
 
lapply(unique(naturevalues$Description), FUN = function(des)
  {
    try({modlss <- loess(yval ~ year, 
                    data = naturevalues[Description%in% des ,])
    pred = predict(modlss, naturevalues[Description%in% des ,], se = T)
    naturevalues[Description%in% des , fit := pred$fit]
    naturevalues[Description%in% des , se := pred$se]})
  }
    )
 
setkey(naturevalues, Description, year)

namesvals = unique(naturevalues$Description)

hc <- highchart() %>% 
  hc_add_series(naturevalues, type = "scatter",
                 hcaes(x = year, y = yval,  group = Description),
                id = namesvals) %>%
  # #hc_add_series(mylist[[2]], type = "line", hcaes(x = year, y = .fitted, group = Description),
  #           name = "Trend", id = "Trend") %>%
  hc_yAxis(min = 0)  %>%
    hc_xAxis( 
         lineWith = 5, 
         labels = list(align = "left", 
                       style = list(
                          fontSize = "16px", 
                          fontWeight = "bold",
                          color = "blue"
                      )))%>%
hc_tooltip(formatter= JS("function () { return 'Injury Nature:<br />  ' + 
   this.series.name }"))

if(!is.null(naturevalues$fit)){
hc <- hc %>% hc_add_series(naturevalues, type = "areasplinerange",
                hcaes(x = year, low = fit - 2*se,
                      high = fit + 2*se, group = Description),
                       linkedTo = namesvals,
                 color = hex_to_rgba("gray", 0.1),  # put a semi transparent color
                
    zIndex = -3 # this is for put the series in a back so the points are showed first
                )
}


hc}

})


```

###Body Part
```{r}

renderHighchart ({
  
 naturevalues = bpplot()
 
 if(nrow(naturevalues)>1){
 
lapply(unique(naturevalues$Description), FUN = function(des)
  {
    try({modlss <- loess(yval ~ year, 
                    data = naturevalues[Description%in% des ,])
    pred = predict(modlss, naturevalues[Description%in% des ,], se = T)
    naturevalues[Description%in% des , fit := pred$fit]
    naturevalues[Description%in% des , se := pred$se]})
  }
    )
 
setkey(naturevalues, Description, year)

namesvals = unique(naturevalues$Description)

hc <- highchart() %>% 
  hc_add_series(naturevalues, type = "scatter",
                 hcaes(x = year, y = yval,  group = Description),
                id = namesvals) %>%
  # #hc_add_series(mylist[[2]], type = "line", hcaes(x = year, y = .fitted, group = Description),
  #           name = "Trend", id = "Trend") %>%
   hc_yAxis(min = 0)  %>%
    hc_xAxis( 
         lineWith = 5, 
         labels = list(align = "left", 
                       style = list(
                          fontSize = "16px", 
                          fontWeight = "bold",
                          color = "blue"
                      )))%>%
hc_tooltip(formatter= JS("function () { return 'Body Part:<br />  ' + 
   this.series.name }"))

if(!is.null(naturevalues$fit)){

 hc <- hc %>% hc_add_series(naturevalues, type = "areasplinerange",
                hcaes(x = year, low = fit - 2*se,
                      high = fit + 2*se, group = Description),
                       linkedTo = namesvals,
                 color = hex_to_rgba("gray", 0.1),  # put a semi transparent color
                
    zIndex = -3 # this is for put the series in a back so the points are showed first
                )
}


hc
}

})



```

###Source
```{r}

renderHighchart ({
  
 naturevalues = sourceplot()
 
 if(nrow(naturevalues)>1){
 
lapply(unique(naturevalues$Description), FUN = function(des)
  {
    try({modlss <- loess(yval ~ year, 
                    data = naturevalues[Description%in% des ,])
    pred = predict(modlss, naturevalues[Description%in% des ,], se = T)
    naturevalues[Description%in% des , fit := pred$fit]
    naturevalues[Description%in% des , se := pred$se]})
  }
    )
 
setkey(naturevalues, Description, year)

namesvals = unique(naturevalues$Description)

hc <- highchart() %>% 
  hc_add_series(naturevalues, type = "scatter",
                 hcaes(x = year, y = yval,  group = Description),
                id = namesvals) %>%
  # #hc_add_series(mylist[[2]], type = "line", hcaes(x = year, y = .fitted, group = Description),
  #           name = "Trend", id = "Trend") %>%
  hc_yAxis(min = 0)  %>%
    hc_xAxis( 
         lineWith = 5, 
         labels = list(align = "left", 
                       style = list(
                          fontSize = "16px", 
                          fontWeight = "bold",
                          color = "blue"
                      )))%>%
hc_tooltip(formatter= JS("function () { return 'Injury Source:<br />  ' + 
   this.series.name }"))

if(!is.null(naturevalues$fit)){

 hc <- hc %>% hc_add_series(naturevalues, type = "areasplinerange",
                hcaes(x = year, low = fit - 2*se,
                      high = fit + 2*se, group = Description),
                       linkedTo = namesvals,
                 color = hex_to_rgba("gray", 0.1),  # put a semi transparent color
                
    zIndex = -3 # this is for put the series in a back so the points are showed first
                )
}

hc}

})


```

###Event
```{r}

renderHighchart ({
  
 naturevalues = eventplot()
 
 if(nrow(naturevalues)>1){
 
lapply(unique(naturevalues$Description), FUN = function(des)
  {
    try({modlss <- loess(yval ~ year, 
                    data = naturevalues[Description%in% des ,])
    pred = predict(modlss, naturevalues[Description%in% des ,], se = T)
    naturevalues[Description%in% des , fit := pred$fit]
    naturevalues[Description%in% des , se := pred$se]})
  }
    )
 
setkey(naturevalues, Description, year)

namesvals = unique(naturevalues$Description)

hc <- highchart() %>% 
  hc_add_series(naturevalues, type = "scatter",
                 hcaes(x = year, y = yval,  group = Description),
                id = namesvals) %>%
  # #hc_add_series(mylist[[2]], type = "line", hcaes(x = year, y = .fitted, group = Description),
  #           name = "Trend", id = "Trend") %>%
  
  hc_yAxis(min = 0)  %>%
    hc_xAxis( 
         lineWith = 5, 
         labels = list(align = "left", 
                       style = list(
                          fontSize = "16px", 
                          fontWeight = "bold",
                          color = "blue"
                      )))%>%
hc_tooltip(formatter= JS("function () { return 'Event:<br />  ' + 
   this.series.name }"))

if(!is.null(naturevalues$fit)){

 hc <- hc %>% hc_add_series(naturevalues, type = "areasplinerange",
                hcaes(x = year, low = fit - 2*se,
                      high = fit + 2*se, group = Description),
                       linkedTo = namesvals,
                 color = hex_to_rgba("gray", 0.1),  # put a semi transparent color
                
    zIndex = -3 # this is for put the series in a back so the points are showed first
                )
}


hc
}

})


```

### Overall Trend

```{r}


renderHighchart ({
  
 naturevalues = copy(natureplot())
 if(nrow(naturevalues)>1){
 
 naturevalues[, yval := sum(yval), by = year]
 

    try({modlss <- loess(yval ~ year, 
                    data = naturevalues)
    pred = predict(modlss, naturevalues, se = T)
    naturevalues[ , fit := pred$fit]
    naturevalues[ , se := pred$se]})
 

 
 
setkey(naturevalues, year)



hc <- highchart() %>% 
  hc_add_series(naturevalues, type = "scatter",
                 hcaes(x = year, y = yval),
                id = "Rate", name = input$ycol) %>%
  # #hc_add_series(mylist[[2]], type = "line", hcaes(x = year, y = .fitted, group = Description),
  #           name = "Trend", id = "Trend") %>%
  
  hc_yAxis(min = min(naturevalues$yval, na.rm=T) ) %>%
    hc_xAxis( 
         lineWith = 5, 
         labels = list(align = "left", 
                       style = list(
                          fontSize = "16px", 
                          fontWeight = "bold",
                          color = "blue"
                      )))%>%
hc_tooltip(formatter= JS("function () { return this.series.name }"))

if(!is.null(naturevalues$fit)){

 hc <- hc %>% hc_add_series(naturevalues, type = "areasplinerange",
                hcaes(x = year, low = fit - 2*se,
                      high = fit + 2*se),
                       linkedTo = "Rate", name = input$ycol,
                 color = hex_to_rgba("gray", 0.1),  # put a semi transparent color
                
    zIndex = -3 # this is for put the series in a back so the points are showed first
                )
}


hc
}

})

```

Circumstances
=============================

##Most common circumstances

``` {r}

circumdata <- reactive({
  
 
  temp = selectedData()[, .N, list(`Oiics Accdt Type Code Desc 2`,
                `Oiics Srce Code Desc 3`,
                `Oiics Nat Code Desc 3`,
                `Oiics Body Part Code Desc`)]
  temp = setorderv(temp[!is.na(N) ], c("N"), 
                   order = -1, 
            na.last=FALSE)
  temp[N>=5,]
  
  })

renderDataTable(datatable(circumdata()  , 
                          options = list(pageLength = 100,
                                         rownames = F))) 


# dig = 2
# sum(str_count(data$`Injry Oiics Srce Code`)<dig)
# sum(str_count(data$`Injry Oiics Nat Code`)<dig)
# sum(str_count(data$`Injry Oiics Body Part Code`)<dig)
# sum(str_count(data$`Injry Oiics Accdt Type Code`)<dig)
 
```

